name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            gradle_args: publishIosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishIosArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishIosSimulatorArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishTvosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishTvosArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishTvosSimulatorArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishTvosSimulatorArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishWatchosArm32PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishWatchosArm64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishWatchosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishWatchosSimulatorArm64PublicationToSonatypeRepository

          - os: macos-latest
            gradle_args: publishMacosX64PublicationToSonatypeRepository
          - os: macos-latest
            gradle_args: publishMacosArm64PublicationToSonatypeRepository

          - os: ubuntu-latest
            gradle_args: publishKotlinMultiplatformPublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: jvmTest publishJvmPublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: publishLinuxX64PublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: publishArmX64PublicationToSonatypeRepository
          - os: ubuntu-latest
            gradle_args: publishMingwX64PublicationToSonatypeRepository

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 8
      - name: Build using gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.gradle_args }}
        env:
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
